-- AllPlayed-koKR.lua
-- $Id$
if not AllPlayed_revision then AllPlayed_revision = {} end
AllPlayed_revision.koKR	= ("$Revision$"):match("(%d+)")


local L = LibStub("AceLocale-3.0"):NewLocale("AllPlayed", "koKR")
if not L then return end


-- Faction names
--		L["Alliance"]                                            				= "얼라이언스"
--		L["Horde"]                                               				= "호드"

-- Tablet title
L["All Played Breakdown"]                                				= "모든 플레이한 내역"

-- Menus
L["AllPlayed Configuration"]													= "AllPlayed 설정"
L["Version %s (r%s)"]																= "버전 %s (r%s)"
L["Display"]                                             				= "화면"
L["Set the display options"]                             				= "화면 표시 설정"
L["All Factions"]                                        				= "모든 진영"
L["All factions will be displayed"]                      				= "모든 진영을 표시합니다."
L["All Realms"]                                          				= "모든 계정"
L["All realms will de displayed"]                        				= "모든 계정을 표시합니다."
L["Show Played Time"]																= "플레이한 시간 표시"
L["Display the played time and the total time played"]					= "플레이한 시간과 플레이한 시간의 총계를 표시합니다."
L["Show Seconds"]                                        				= "초 표시"
L["Display the seconds in the time strings"]             				= "시간 문자열에 초를 표시합니다."
L["Show Gold"]                                    						= "소지금 표시"
L["Display the gold each character pocess"]     							= "캐릭터 별 소지금을 표시합니다."
L["Show XP Progress"]                                    				= "경험치 상태 표시"
L["Display XP progress as a decimal value appended to the level"]	= "레벨에 소수점을 추가해 경험치 상태를 표시합니다."
L["Show XP total"]																	= "경험치 총계 표시"
L["Show the total XP for all characters"]									= "모든 캐릭터에 대한 총 경험치를 표시합니다."
L["Rested XP"]                                           				= "휴식경험치"
L["Set the rested XP options"]                                   	= "휴식경험치 표시 설정"
L["Rested XP Total"]                                             	= "휴식경험치 총계"
L["Show the character rested XP"]                                	= "캐릭터 휴식경험치를 표시합니다."
L["Percent Rest"]                                                	= "휴식상태 백분율"
L["Set the base for % display of rested XP"]                     	= "휴식경험치를 %로 표시하도록 기본 설정합니다."
L["Rested XP Countdown"]                                         	= "휴식경험치 초읽기"
L["Show the time remaining before the character is 100% rested"]	= "캐릭터가 100% 휴식하기 전 남은 시간을 표시합니다."
L["PVP"]																				= "PVP"
L["Set the PVP options"]															= "PVP 표시 설정"
L["Arena Points"]																	= "투기장 점수"
L["Show the character arena points"]											= "캐릭터 투기장 점수를 표시합니다."
L["Honor Points"]																	= "명예 점수"
L["Show the character honor points"]											= "캐릭터 명예 점수를 표시합니다."
L["Honor Kills"]																	= "명예 승수"
L["Show the character honor kills"]											= "캐릭터 명예 승수를 표시합니다."
L["Show PVP Totals"]																= "PVP 총계 표시"
L["Badges of Justice"]															= "정의의 문장"
L["Show the character badges of Justice"]									= "캐릭터의 정의의 문장을 표시합니다."
L["WG Marks"]																		= "노래방 점수"
L["Show the Warsong Gulch Marks"]												= "전쟁노래 협곡 점수를 표시합니다."
L["AB Marks"]																		= "분지 점수"
L["Show the Arathi Basin Marks"]												= "아라시 분지 점수를 표시합니다."
L["AV Marks"]																		= "알방 점수"
L["Show the Alterac Valley Marks"]											= "알터랙 계곡 점수를 표시합니다."
L["EotS Marks"]																		= "폭눈 점수"
L["Show the Eye of the Storm Marks"]											= "폭풍의 눈 점수를 표시합니다."
L["Show the honor related stats for all characters"]					= "모든 캐릭터에 대한 명예 상태를 표시합니다."
L["Show Class Name"]                                     				= "직업명 표시"
L["Show the character class beside the level"]           				= "레벨 옆에 캐릭터의 직업을 표시합니다."
L["Show Location"]																	= "위치 표시"
L["Show the character location"]												= "캐릭터의 위치를 표시합니다."
L["Don't show location"]															= "위치를 표시하지 않음"
L["Show zone"]																		= "지역 표시"
L["Show subzone"]																	= "세부지역 표시"
L["Show zone/subzone"]															= "지역/세부지역 표시"
L["Colorize Class"]                                  	    			= "직업별 색상화"
L["Colorize the character name based on class"]      	    			= "직업을 기준으로 캐릭터 이름을 색상화합니다."
L["Use Old Shaman Colour"]														= "구 주술사 색상 사용"
L["Use the pre-210 patch colour for the Shaman class"]					= "주술사 직업에 대해 공개210 패치 색상을 사용합니다."
L["Sort Type"]																		= "정렬 형식"
L["Select the sort type"]														= "정렬 형식을 선택합니다."
L["By name"]																			= "이름"
L["By level"]																		= "레벨"
L["By experience"]																	= "경험치"
L["By rested XP"]																	= "휴식경험치"
L["By % rested"]																	= "% 휴식"
L["By money"]																		= "소지금"
L["By time played"]																= "플레이한 시간"
L["Sort in reverse order"]														= "역순으로 정렬"
L["Use the curent sort type in reverse order"]							= "역순으로 현재 정렬 형식을 사용합니다."
L["Use Icons"]																		= "아이콘 사용"
L["Use graphics for coin and PvP currencies"]								= "주화와 PVP 화폐를 위한 그래픽을 사용합니다."
L["Minimap Icon"]																	= "미니맵 아이콘"
L["Show Minimap Icon"]															= "미니맵 아이콘 표시"
L["Scale"]																			= "크기"
L["Scale the tooltip (70% to 150%)"]											= "툴팁의 크기 (70% - 150%)"
L["Opacity"]      																	= "투명도"
L["% opacity of the tooltip background"]									= "툴팁 배경의 투명도 %"
L["Sort"]																				= "정렬"
L["Set the sort options"]														= "정렬 표시 설정"
L["Ignore Characters"]                                      			= "캐릭터 제외"
L["Hide characters from display"]                           			= "화면상에 캐릭터를 숨깁니다."
L["%s : %s"]																			= "%s : %s"
L["Hide %s of %s from display"]												= "화면에 %s - %s를 숨깁니다."
L["BC Installed?"]                                          			= "불성 설치됨?"
L["Is the Burning Crusade expansion installed?"]            			= "불타는 성전 확장팩이 설치되어 있습니까?"
L["Close"]                                        	       			= "닫기"
L["Close the tooltip"]                            	       			= "툴팁 닫기"
L["None"]                                         	       			= "없음"
L["100%"]																				= "100%"
L["150%"]																				= "150%"

-- Strings
L["v%s - %s (Type /ap for help)"]                 	       			= "v%s - %s (도움말을 보려면 /ap)"
L["%s characters "]                               	       			= "%s 캐릭터 "
L["%d rested XP"]                                 	    				= "%d 휴식경험치"
L["rested"]                                       		        		= "휴식"
L["Total %s Time Played: "]                              				= "%s 총 시간 플레이: "
L["Total %s Cash Value: "]                               				= "%s 총 소지금: "
L["Total Time Played: "]                                 				= "총 플레이한 시간: "
L["Total Cash Value: "]                                  				= "총 소지금: "
L["Total PvP: "]																	= "PvP 총계: "
L["Total XP: "]																		= "경험치 총계: "
L["Unknown"]																			= "알수없음"
L["%.1f M XP"]																		= "%.1f 백만 경험치"
L["%.1f K XP"]																		= "%.1f 천 경험치"
L["%d XP"]																			= "%d 경험치"
L['%s HK']																			= "%s 명승"
L['%s HP']																			= "%s 명점"
L['%s AP']																			= "%s 투점"
L['%s BoJ']																			= "%s 정의"
L['%s AB']																			= "%s 분지"
L['%s AV']																			= "%s 알방"
L['%s WG']																			= "%s 노래방"
L['%s EotS']																			= "%s 폭눈"

-- Console commands
--		L["/allplayed"]                                   	       			= true,
--		L["/ap"]                                          	       			= true,
--		L["/allplayedcl"]                                          			= true,
--		L["/apcl"]                                                 			= true"

